### ISSUE TITLE
I would like to propose a new feature, but my English is not very good

### ISSUE THREAD

**Issue by Enthlinn** [VenoMKO/TMM#1]
On TW server The game launcher will check client integrity,But tera.exe will not read CompositePackageMapper.dat immediately, it will wait for XIGNCODE to be loaded before reading,MOD can be used by replacing CompositePackageMapper.dat when XIGNCODE is loaded

**Comment by VenoMKO** [comment]
Hi! I am aware of the issue. I do plan to add a feature that will patch the CompositePackageMapper file on Tera launch to bypass KR\TW integrity checks.

**Comment by VenoMKO** [comment]
Check TMM v.1.20. It should work fine.
