### ISSUE TITLE
cant get it working TMM

### ISSUE THREAD

**Issue by MysticSushie** [VenoMKO/TMM#3]
im trying to do a file  and i cant open the program idk what i did wrong but after the specify thing and i click apply idk what to do or how to launch it

**Comment by VenoMKO** [comment]
After specifying the game folder you should see TMM window. Press **Add** and select your mod file.

**Comment by MysticSushie** [comment]
do u have anyway i could contact u im so confused on how to get it working lol im new to tera modding
